RuleList/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.GetAllDevice,name='getkey'),
    #url(r'(?P<deviceID>\w+)/(?P<channelID>\w+)/$',views.GetDeviceRuleChannel,name='getRuleByID'),
    url(r'rule/(?P<ruleID>(.+))/$',views.GetRuleByRuleID,name='getRuleByRuleID'),
    url(r'addRule/(?P<deviceID>(.+))/(?P<channelID>(.+))/$',views.AddRuleByDeviceID,name='AddRuleByDeviceID'),
    url(r'deleteRule/(?P<ruleID>(.+))/$',views.deleteRuleByRuleID,name='DeleteRuleByDeviceID'),
    ]

deviceRule/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()
urlpatterns = [
    url(r'^accounts/', admin.site.urls),
    url(r'^deviceRule/',include('RuleList.urls')),

]

RuleList/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib import admin
# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
class UserAdmin(admin.ModelAdmin):
    list_display = ('username', 'password')
admin.site.register(User)

RuleList/forms.py
#!/usr/bin/env python
# coding=utf-8
from django import forms
from django.utils.translation import ugettext, ugettext_lazy as _
class RuleForm(forms.Form):
    Name=forms.CharField(label="规则名称",required=True,max_length=50)
    StreamIndex=forms.ChoiceField(label="分析码流",choices=[(0,"主码流"),(1,"辅码流")])
    EventLevel=forms.ChoiceField(label="事件等级",choices=[(0,0),(1,1),(2,2),(3,3)])
    IsActive=forms.ChoiceField(label="是否激活",required=True,choices=[(0,"不激活"),(1,"激活")],widget=forms.RadioSelect)
    ServiceID=forms.ChoiceField(label="隶属服务")
    EventSourceID=forms.ChoiceField(label="分析算法")
    EventSourceConfig=forms.CharField(label="配置文件",required=False,widget=forms.Textarea)
class RuleAdd(forms.Form):
    Name=forms.CharField(label="规则名称",required=True,max_length=50,error_messages={"required":"规则名称不能为空"})
    StreamIndex = forms.ChoiceField(label="分析码流", choices=[(0, "主码流"), (1, "辅码流")])
    EventLevel=forms.ChoiceField(label="事件等级",choices=[(0,0),(1,1),(2,2),(3,3)])
    IsActive=forms.ChoiceField(label="是否激活",required=True,choices=[(0,"不激活"),(1,"激活")],widget=forms.RadioSelect)
    ServiceID=forms.ChoiceField(label="隶属服务")
    EventSourceID=forms.ChoiceField(label="分析算法")
    EventSourceConfig = forms.CharField(label="配置文件", required=False,widget=forms.Textarea)
    def __init__(self,*args,**kwargs):
        super(RuleAdd,self).__init__(*args)
        self.fields["ServiceID"].choices=kwargs["ServiceChoices"]
        self.fields["EventSourceID"].choices=kwargs["EventSourceChoices"]
    # def clean(self):
    #     raise forms.ValidationError("Please input correct username")
    #     print(1)

RuleList/views.py
#!/usr/bin/env python
# coding=utf-8
from django.shortcuts import render
from django.conf import settings
from django.core.cache import cache as redisConn
from django.contrib.auth import authenticate,login
from  .forms import RuleForm,RuleAdd
import json,redis
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from models import User
import traceback,copy
import RuleOperation

def getServiceAndEventSource():
    '''
    从上层服务获取service和EventSource列表
    '''
    serviceAndEvent = RuleOperation.getServiceAndEventSource()
    sourceList = []
    for source in serviceAndEvent["eventSource"]:
        for k, v in source.items():
            sourceForm = (k, v)
            sourceList.append(sourceForm)
    serviceList = []
    for source in serviceAndEvent["serviceList"]:
        for k, v in source.items():
            sourceForm = (k, v)
            serviceList.append(sourceForm)
    return serviceList,sourceList
@login_required
def GetAllDevice(request):
    '''
    获取所有设备，以及上面的规则，以json格式渲染到html中
    :param request:
    :return:
    '''
    print(request)
    try:
        jsonTree=RuleOperation.getAlldevice()
        if jsonTree:
            message=request.GET.get("message")
            if message:
                DetailData=message
            else:
                DetailData=''
            context={"aa":json.dumps(jsonTree),"DetailData":DetailData}
        else:
            context={"aa":None,"DetailData":"没有设备，请先添加设备~"}
    except Exception,ex:
        traceback.print_exc()
        context={"aa":None,"DetailData":ex}
    finally:
        return render(request, 'rulelist/test.html', context)

def GetDeviceRuleChannel(request,deviceID,channelID):
    '''
    根据设备ID和通道ID获取通道上面的规则
    :param request:
    :param deviceID:
    :param channelID:
    :return:
    '''
    redisID=":{0}:{1},{2}".format("ruleDevice",deviceID,channelID)
    ruleIdList=redisConn.smembers(redisID)
    #ruleIdList=redisConn.get(":ruleDevice:17763917-051e-4508-9ff3-d3bd186fa4c1_0")
    if len(ruleIdList)==0:
        return HttpResponse("This channel has not any rule!!")
    try:
        ruleList=RuleOperation.getDeviceRuleList(ruleIdList)
        if ruleList:
            context={"ruleList":ruleList}
        else:
            context={"ruleList":None}
    except RuntimeError,ex:
        context={"ruleList":None}
    finally:
        return render(request, 'rulelist/redis.html', context)

def GetRuleByRuleID(request,ruleID):
    '''
    根据规则ID，获取规则，展示规则
    :param request:
    :param ruleID:
    :return:
    '''
    try:
        if request.method=='POST':
            ruleEditData=request.POST.copy()
            ruleEditData["ruleID"]=ruleID
            flag=RuleOperation.updateRule(ruleEditData)
            if flag==False:
                return HttpResponseRedirect('/deviceRule/?message=修改失败')
            else:
                return HttpResponseRedirect('/deviceRule/?message=修改成功')
        else:
            rule=RuleForm()
            AssembleRule=RuleOperation.getDeviceRule(ruleID)
            if AssembleRule:
                sourceList=[]
                for source in AssembleRule.SourceList:
                    for k,v in source.items():
                        sourceForm=(k,v)
                        sourceList.append(sourceForm)
                rule.fields["EventSourceID"].choices=sourceList
                rule.fields["EventSourceID"].initial = AssembleRule.baseRule.EventSourceID
                serviceList=[]
                for service in AssembleRule.ServList:
                    for k,v in service.items():
                        serviceList.append((k,v))
                rule.fields["ServiceID"].choices=serviceList
                rule.fields["ServiceID"].initial=AssembleRule.baseRule.ServiceID
                rule.fields["Name"].initial=AssembleRule.baseRule.Name
                #rule.fields["level"].choices=[(0,0),(1,3),(2,4),(3,5),(4,6)]
                rule.fields["EventLevel"].initial=AssembleRule.baseRule.EventLevel
                rule.fields["EventSourceConfig"].initial=AssembleRule.baseRule.ConfigData
                if AssembleRule.baseRule.IsActive:
                    rule.fields["IsActive"].initial=1
                else:
                    rule.fields["IsActive"].initial=0
                if AssembleRule.baseRule.StreamIndex==1:
                    rule.fields["StreamIndex"].initial=1
                else:
                    rule.fields["StreamIndex"].initial=0
                return render(request,'rulelist/ruleDetail.html',{'form':rule})
            else:
                return render(request,'rulelist/error.html',context={"DetailData":"没有此规则，或者此规则刚刚删除，请刷新页面！"})
    except RuntimeError,ex:
        traceback.print_exc()
        return render(request, 'rulelist/error.html', {'DetailData': ex})

def deleteRuleByRuleID(request,ruleID):
    '''
    根据规则ID，删除指定的规则
    :param request:
    :param ruleID:
    :return:
    '''
    try:
        flag=RuleOperation.deleteRule(ruleID)
        if flag==0:
            return HttpResponse("删除成功")
        else:
            return HttpResponse("删除失败")
    except:
        traceback.print_exc()
        return HttpResponse("删除失败")

def AddRuleByDeviceID(request,deviceID,channelID):
    '''
    根据设备ID和通道ID,，添加到此设备通道上
    :param request:
    :param deviceID:
    :param channelID:
    :return:
    '''
    try:
        if request.method=="POST":
            serviceList,sourceList=getServiceAndEventSource()
            form=RuleAdd(request.POST,ServiceChoices=serviceList,EventSourceChoices=sourceList)
            # rule=RuleAdd(request.POST)
            rule = request.POST.copy()
            rule["DeviceID"]=deviceID
            rule["ChannelIndex"]=int(channelID)
            flag=RuleOperation.addRule(rule)
            if flag==False:
                return HttpResponseRedirect('/deviceRule/?message=修改失败')
            else:
                return HttpResponseRedirect('/deviceRule/?message=添加失败')
        else:
            serviceList,sourceList=getServiceAndEventSource()
            rule=RuleAdd(ServiceChoices=serviceList,EventSourceChoices=sourceList)
            rule.fields["IsActive"].initial=0
            return render(request, 'rulelist/ruleDetail.html', {'form': rule})
    except Exception,ex:
        traceback.print_exc()
        message='/deviceRule/?message=调用ice接口发生错误，或者提交表时发生错误！！错误详情：{0}'.format(ex)
        return HttpResponseRedirect(message)

RuleList/templates/rulelist/bootstrap.html
<head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bootstrap中文网开源项目免费 CDN 服务</title><meta name="description" content="Bootstrap中文网开源项目免费 CDN 服务 - 我们致力于为Bootstrap一样优秀的开源项目提供稳定、快速的免费 CDN 服务"><meta name="keywords" content=""><meta name="author" content="Bootstrap中文网"><link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"><link href="//cdn.bootcss.com/font-awesome/4.3.0/css/font-awesome.css" rel="stylesheet"><link href="/assets/css/site.min.css" rel="stylesheet"><!--[if lt IE 9]>
    <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
  <![endif]--><!--[if IE 9]>
    <script src="//cdn.bootcss.com/geopattern/1.2.3/js/base64.min.js"></script>
    <script src="//cdn.bootcss.com/geopattern/1.2.3/js/typedarray.min.js"></script>
  <![endif]--><script>var _hmt = _hmt || [];</script><link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png"><link rel="shortcut icon" href="/assets/ico/favicon.ico"></head>

RuleList/templates/rulelist/error.html
{% load staticfiles %}
{% load bootstrap %}
{{ DetailData }}

RuleList/templates/rulelist/redis.html
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/html">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link href="http://cdn.bootcss.com/bootstrap/3.2.0/css/bootstrap.css" rel="stylesheet">
        <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
        <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <script src="http://cdn.bootcss.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="/static/bootstrap-treeview/bootstrap-treeview.js" type="text/javascript"></script>
        <!--[if lt IE 9]>
          <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
         <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
         <![endif]-->
    </head>
    <body>
    <div class="bs-example bs-example-tabs">
    <ul id="myTab" class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">规则一</a></li>
      <li role="presentation" class=""><a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false">规则二</a></li>
        <li role="presentation" class=""><a href="#profile1" role="tab" id="profile1-tab" data-toggle="tab" aria-controls="profile1" aria-expanded="false">规则三</a></li>
        </ul>
      </li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div role="tabpanel" class="tab-pane fade active in" id="home" aria-labelledby="home-tab">
        <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab">
        <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="profile1" aria-labelledby="profile1-tab">
        <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>
      </div>
    </div>
  </div>
    </body>

RuleList/templates/rulelist/ruleDetail.html
{% load staticfiles %}
{% load bootstrap %}
{{ form.non_field_errors }}
<form action={{ request.path }} method="post">
    {% csrf_token %}
{#    {% for field in form|bootstrap %}#}
{#        <div class="fieldWrapper">#}
{#            {{ field.label }}:{{ field }}#}
{#            {{ field.errors }}#}
{#        </div>#}
{#    {% endfor %}#}
    {{ form | bootstrap }}
    <div>
    <input type="submit" value="提交"/>
    </div>
</form>

RuleList/templates/rulelist/test.html
{% load staticfiles %}
{% load bootstrap %}
<html xmlns="http://www.w3.org/1999/html">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link href="http://cdn.bootcss.com/bootstrap/3.2.0/css/bootstrap.css" rel="stylesheet">
        <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
        <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <script src="http://cdn.bootcss.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="/static/bootstrap-treeview/bootstrap-treeview.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="/static/css/udf.css">
        <!--[if lt IE 9]>
          <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
         <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
         <![endif]-->
    </head>
    <body>
        <div id="container">
            <div id="header">
                <div id="branding">
                    <h1 id="site-name" ><a href="">规则展示</a></h1>
                </div>
             </div>
            <div id="content">
            <div class="row">
                <div class="col-md-3" style="height:800px; overflow:auto">
                    <div class="form-group">
                        <label for="input-select-node" class="sr-only"></label>
                        <input type="input" class="form-control" id="input-select-node" placeholder="Identify node..." value="">
                    </div>
                    <div id="tree">
                    </div>
                </div>
                <div class="col-md-3">
                    <div id="data1" style="display: block">
                        {{ DetailData }}
                    </div>
                </div>
            </div>
                </div>
        </div>
      </body>
        <script type="text/javascript">
            var submit= function (object) {
                alert(1);
            }
            var addRule= function (obj) {
                var href=obj.parentNode.getAttribute('selecturi')
                $("#data1").load(href)
            }
            var deleteRule=function (obj) {
                if(confirm("你确定要删除此规则么，没事，我保证不打你。。。。")) {
                    var href = obj.parentNode.getAttribute('selecturi')
                    ruleID = href.split('/')
                    len = ruleID.length
                    ruleID[2] = "deleteRule"
                    newUrl = ruleID.join("/")
                    $("#data1").load(newUrl)
                }
            }
            var reload
            $(function  (){
                function getTree() {
                    var data1={{ aa|safe }}
                    return data1;
            }

            var obj={};
            obj.text="123";
{#            $('#tree').treeview({#}
{#                data:getTree(),#}
{#                color:"#428bca",#}
{#                showTags:true,#}
{#                enableLinks:true,#}
{#                onNodeSelected:function (event,data) {#}
{#                    var href=data.href#}
{#                    $("#data1").load(href)#}
{#                }#}
{#            });#}
            var initSelectableTree = function() {
                return $('#tree').treeview({
                    data: getTree(),
                    levels:1,
                    color:"#428bca",
                    showTags:true,
                    enableLinks:false,
                    multiSelect: $('#chk-select-multi').is(':checked'),
                    onNodeSelected:function (event,data) {
                        if (!data.nodes) {
                            var href = data.href;
                            $("#data1").load(href);
                        }
                    },
                    onNodeUnselected:function (event,data) {
                        $("#data1").empty()
                    }

              })
            };
            var $selectableTree = initSelectableTree();

            var findSelectableNodes = function() {
              return $selectableTree.treeview('search', [ $('#input-select-node').val(), { ignoreCase: true, exactMatch: false } ]);
            };
             var selectableNodes = findSelectableNodes();

{#            $('#chk-select-multi:checkbox').on('change', function () {#}
{#              console.log('multi-select change');#}
{#              $selectableTree = initSelectableTree();#}
{#              selectableNodes = findSelectableNodes();#}
{#            });#}

            // Select/unselect/toggle nodes
            $('#input-select-node').on('keyup', function (e) {
                $selectableTree.treeview('collapseAll', { silent: false });
                selectableNodes = findSelectableNodes();
                $('.select-node').prop('disabled', !(selectableNodes.length >= 1));
            });
{#    #}
{#            $('#btn-select-node.select-node').on('click', function (e) {#}
{#              $selectableTree.treeview('selectNode', [ selectableNodes, { silent: $('#chk-select-silent').is(':checked') }]);#}
{#            });#}
{#    #}
{#            $('#btn-unselect-node.select-node').on('click', function (e) {#}
{#              $selectableTree.treeview('unselectNode', [ selectableNodes, { silent: $('#chk-select-silent').is(':checked') }]);#}
{#            });#}
{#    #}
{#            $('#btn-toggle-selected.select-node').on('click', function (e) {#}
{#              $selectableTree.treeview('toggleNodeSelected', [ selectableNodes, { silent: $('#chk-select-silent').is(':checked') }]);#}
{#            });#}

            })
        </script>
</html>

RuleList/templates/rulelist/test_bak.html
<form action="/accounts/login/?next=/accounts/" method="post" id="login-form"><input type="hidden" name="csrfmiddlewaretoken" value="kOhiI4YJdxVkTFDNIvyWeyrXuvMiLl1lIAlD7G6GB8PlaY2q1sPznxW9lIjKfJZ4">
  <div class="form-row">

    <label class="required" for="id_username">Username:</label> <input autofocus="" id="id_username" maxlength="254" name="username" type="text" value="administrat" required="">
  </div>
  <div class="form-row">

    <label class="required" for="id_password">Password:</label> <input id="id_password" name="password" type="password" required="">
    <input type="hidden" name="next" value="/accounts/">
  </div>


  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="Log in">
  </div>
</form>

<form action="/deviceRule/addRule/1078ef2e-1d7c-4e79-84d6-fbf6d829e2a2/0/" method="post">
    <input type="hidden" name="csrfmiddlewaretoken" value="oWgAqy7RJ83Se3MsSni1UrILiLGiqsJUrPfx235HZdvMrMpaTlxJAuW4ex5OkZKr">













<div class="form-group">


            <label class="control-label  required" for="id_Name">规则名称</label>


        <div class=" ">
            <input class=" form-control" id="id_Name" maxlength="50" name="Name" type="text" required="">




        </div>

</div>




<div class="form-group">


            <label class="control-label  required" for="id_StreamIndex">分析码流</label>


        <div class=" ">
            <select class=" form-control" id="id_StreamIndex" name="StreamIndex" required="">
<option value="0">主码流</option>
<option value="1">辅码流</option>
</select>




        </div>

</div>




<div class="form-group">


            <label class="control-label  required" for="id_EventLevel">事件等级</label>


        <div class=" ">
            <select class=" form-control" id="id_EventLevel" name="EventLevel" required="">
<option value="0">0</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
</select>




        </div>

</div>




<div class="form-group">


            <label class="control-label  required">是否激活</label>

        <div class="">

                <div class="radio">
                    <label>
                        <input checked="checked" id="id_IsActive_0" name="IsActive" type="radio" value="0" required="">
                        不激活
                    </label>
                </div>

                <div class="radio">
                    <label>
                        <input id="id_IsActive_1" name="IsActive" type="radio" value="1" required="">
                        激活
                    </label>
                </div>





        </div>

</div>




<div class="form-group">


            <label class="control-label  required" for="id_ServiceID">隶属服务</label>


        <div class=" ">
            <select class=" form-control" id="id_ServiceID" name="ServiceID" required="">
<option value="8d51bcaf-34ef-43b0-b742-61235c91d5b0">人群聚集</option>
<option value="7f133a36-37c0-4f3c-906f-c9ab7af8fd1f">入侵检测</option>
<option value="1c13845f-482e-4806-943d-507088e42751">视频诊断</option>
<option value="c6731d30-c872-11e3-a896-00e081e85edb">徘徊检测</option>
<option value="dac8a76d-4714-11e5-b503-90b11c4f1625">LNG手套检测</option>
<option value="24be1d72-bdd2-11e2-9a27-00155d011700">人脸检测</option>
<option value="8257688f-bdd1-11e2-9a27-00155d011700">偷盗检测</option>
<option value="178b2db5-f9bd-11e2-a1ee-00155d011700">打架斗殴检测</option>
<option value="18361d2b-4fbd-11e5-b987-90b11c4f1625">LNG吸烟检测</option>
</select>




        </div>

</div>




<div class="form-group">


            <label class="control-label  required" for="id_EventSourceID">分析算法</label>


        <div class=" ">
            <select class=" form-control" id="id_EventSourceID" name="EventSourceID" required="">
<option value="803d5d1e-e33a-45bc-a4b8-bdef75f984e4">analysis_service@172.16.1.28</option>
<option value="3a6d58d7-3217-4a96-8503-9cac18931223">analysis_service_lng@172.16.1.28_lng</option>
</select>




        </div>

</div>




<div class="form-group">


            <label class="control-label  " for="id_EventSourceConfig">配置文件</label>


        <div class=" ">
            <textarea class=" form-control" cols="40" id="id_EventSourceConfig" name="EventSourceConfig" rows="10"></textarea>




        </div>

</div>



    <div>
    <input type="button" value="提交">
    </div>
</form>